### ISSUE TITLE
how to run tests?

### ISSUE THREAD

**Issue by kmike** [ghtdak/qtreactor#14]
Hey,

Test running instructions from README don't work for me:

```
trial --reactor=pyqt4 [twisted] [twisted.test] [twisted.test.test_internet]
[twisted] ...                                                           [ERROR]
[twisted
  test] ...                                                             [ERROR]
  test
    test_internet] ...                                                  [ERROR]

===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/trial/runner.py", line 586, in loadByNames
    things.append(self.findByName(name))
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/trial/runner.py", line 396, in findByName
    return reflect.namedAny(name)
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/python/reflect.py", line 308, in namedAny
    raise ModuleNotFound("No module named %r" % (name,))
twisted.python.reflect.ModuleNotFound: No module named '[twisted]'

[twisted]
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/trial/runner.py", line 586, in loadByNames
    things.append(self.findByName(name))
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/trial/runner.py", line 396, in findByName
    return reflect.namedAny(name)
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/python/reflect.py", line 310, in namedAny
    raise ObjectNotFound('%r does not name an object' % (name,))
twisted.python.reflect.ObjectNotFound: '[twisted.test]' does not name an object

[twisted.test]
===============================================================================
[ERROR]
Traceback (most recent call last):
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/trial/runner.py", line 586, in loadByNames
    things.append(self.findByName(name))
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/trial/runner.py", line 396, in findByName
    return reflect.namedAny(name)
  File "/Users/kmike/envs/splash/lib/python2.7/site-packages/twisted/python/reflect.py", line 310, in namedAny
    raise ObjectNotFound('%r does not name an object' % (name,))
twisted.python.reflect.ObjectNotFound: '[twisted.test.test_internet]' does not name an object

[twisted.test.test_internet]
-------------------------------------------------------------------------------
Ran 3 tests in 0.002s
```

The second example command (`cd <test-directory> && trial` - is `<test-directory>` ghtTests?) does nothing for me.

**Comment by ghtdak** [comment]
Ah, I was trying to use syntax like one finds in git help... Probably did it wrong

Anyway, the command is:

```
 trial --reactor=pyqt4 <the modules from trial you want to run>
```

So, 

```
 trial --reactor=pyqt4 twisted.test.test_internet
```

is a good first try

**Comment by kmike** [comment]
Aha, thanks, it works!

FYI: twisted plugin is not installed by setup.py, so this command only works from a top folder of the source checkout. When executed from anywhere else it prints

```
trial --reactor=pyqt4 twisted.test.test_internet
/Users/kmike/envs/splash/bin/trial: The specified reactor does not exist: 'pyqt4'.
See the list of available reactors with --help-reactors
```

**Comment by ghtdak** [comment]
There is a weird file called "gtrial" in bin, not to be confused with "gtrial.py." This file if in your path is supposed to do something about this.  Its a twisted thing... I think its still in the writeup some place.
